apiVersion: v1
kind: Service
metadata:
  name: jenkins-node-port
spec:
  type: NodePort
  selector:
    app: my_jenkins
    
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30085
