apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-replica-set
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      my-pod: my-jenkins
  template:
    metadata:
      labels:
        my-pod: my-jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
