apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "400m"
          limits:
            memory: "250Mi"
            cpu: "400m"
