apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-replica-set
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      my-pod: my-tomcat
  template:
    metadata:
      labels:
        my-pod: my-tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:latest
